### ISSUE TITLE
Can't get the dashboard working

### ISSUE THREAD

**Issue by patricksmeets** [rkrupinski/cryptocurrency-dashboard#1]
Hello Rafal,

I downloaded your cryptocurrency dashboard project and tried to install it with Yarn but without luck.
Then I downloaded the index.html, vendor.js, main.js and manifest.js from your demosite which worked. But the javascript files are obfuscated so I cannot use them.

I would like to use your code for my own crypto-ticker as I really like the interface but I am totally lost.

The 3 javascript files (vendor.js, main.js and manifest.js) were not in the repository, do I have to generate them one way or the other? Or could you add those in a readable format?

What do I have to do to make changes to your code to adapt it to my requirements?

Your help would be greatly appreciated.

Best regards,

Patrick
(patrick.smeets@icloud.com)

**Comment by rkrupinski** [comment]
Hi,

1. Install `nodejs` along with `yarn`
2. Clone the project
3. Navigate to the root directory (where `package.json` is)
4. Run `yarn` to install all the dependencies (this is gonna take a while...)
5. From there you can either run `yarn start` to launch in dev mode or `yarn run build` to build a ready-to-be-served, bundled, and optimised version of the dashboard (need an http server for that, e.g. `python -m SimpleHTTPServer 8000`)

**Comment by patricksmeets** [comment]
Hi Rafal,

Thanks for your swift reply. Installation of node.js did the trick (I am really a noob).

When I run `yarn run build` it generates the 4 files needed for the dashboard.

The only issue I still have is that when I run `yarn start` I end up with the same situation: 
_........
Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 577 bytes {0} [built]
    [./node_modules/lodash/lodash.js] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Compiled successfully._

It shows also the dashboard. I was expecting to enter some sort of development environment.

- What do I do wrong? How can I change the code itself to modify the dashboard? Do I have to install an editor like Visual Studio Code or ATOM or something like that?

Thanks in advance for your response.

Best regards,
Patrick

**Comment by rkrupinski** [comment]
By “dev mode” I meant the app watching for changes in source files and refreshing automatically to reflect them. It still requires one to bring own code editor.
